import { Box, Button, Container, Typography } from "@mui/material";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Router from "next/router";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { signOut, getSession } from "next-auth/react";
import { GetServerSideProps } from "next";

const Home: NextPage = (): JSX.Element => {
  const { data, status } = useSession();

  useEffect(() => {
    if (status === "unauthenticated") Router.replace("/login");
  }, [status]);

  console.log(data, status);
  if (status === "authenticated") {
    return (
      <Container className={styles.container}>
        <Head>
          <title>My App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box className={styles.main}>
          <Typography className={styles.title}>
            Welcome to The Project ,
          </Typography>
          <Typography style={{ wordBreak: "break-all" }}>
            {"Access token : "}
            {data?.user?.accessToken}
          </Typography>
          <Link href="/blog">
            <Button>STATIC RENDERING</Button>
          </Link>
          <Link href="/user">
            <Button>SERVER SIDE RENDERING</Button>
          </Link>
          <Button onClick={() => signOut()}>LOG OUT</Button>
        </Box>
      </Container>
    );
  }

  return <Container className={styles.container}></Container>;
};

// This is the recommended way for Next.js 9.3 or newer
export const getServerSideProps: GetServerSideProps = async (context: any) => {
  const session = await getSession(context);
  console.log("session,", session, session?.user?.accessToken);
  return {
    props: {
      session,
    },
  };
};

export default Home;
