import { Box, Button, Container, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Container className={styles.container}>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={styles.main}>
        <Typography className={styles.title}>Welcome to The Project</Typography>
        <Link href="/blog">
          <Button>STATIC RENDERING</Button>
        </Link>
        <Link href="/user">
          <Button>SERVER SIDE RENDERING</Button>
        </Link>
      </Box>
    </Container>
  );
};

export default Home;
